### ISSUE TITLE
Potential issues when running in a multithreaded environment

### ISSUE THREAD

**Issue by travisp** [FetLife/rollout#49]
The global variable and global redis connection would seem to cause problems in multithreaded servers, which is becoming a lot more common in Rails deployments (puma is now the recommended server by heroku for Rails). I would love to see rollout handle this seamlessly.

**Comment by imackinn** [comment]
@gabrieljoelc did you ever figure this out? I'm encountering some redis timeouts using rollout in a Puma environment. I'm looking at using @mperham's  connection pool (https://github.com/mperham/connection_pool) to create a pool of redis connections for rollout to use, like so:
```
uri = URI.parse(ENV["REDIS_URL"] || "redis://localhost:6379/" )
$redis = ConnectionPool::Wrapper.new(size: 2, timeout: 5) { Redis.new(:host => uri.host, :port => uri.port, :password => uri.password) }
$rollout = Rollout.new($redis)
```

Any thoughts?

**Comment by gabrieljoelc** [comment]
We never ended up using rollout. However, we use `connection_pool` for RabbitMQ connections in our Sidekiq processes and it works great. We use the `with` method instead of `ConnectionPool::Wrapper` in [la_gear](https://github.com/giftcardzen/la_gear) [here](https://github.com/giftcardzen/la_gear/blob/7c0b350e78759af7f254e7395ae1593a5af5f3d4/lib/la_gear/bus.rb#L5-L8) and [here](https://github.com/giftcardzen/la_gear/blob/7c0b350e78759af7f254e7395ae1593a5af5f3d4/lib/la_gear/bus.rb#L78-L80)
```ruby
# /la_gear/lib/la_gear/bus.rb
def init_pool(size = ::Sidekiq.options[:concurrency],
                       timeout = 3)
      $publisher = ConnectionPool.new(
        size: size,
        timeout: timeout
      ) { ::LaGear::Publisher.new }

      $publisher.with do |bus|
        fail 'Bus is lost!' unless bus.is_a?(LaGear::Publisher)
      end
    end
```
and then in our sidekiq initializer in our Rails apps we do this:
```ruby
# /config/initializers/sidekiq.rb
Sidekiq.configure_server do |config|
  config.redis = { namespace: 'best_app_ever' }
  # we require our sneakers initializer in our sidekiq threads
  require "#{Rails.root}/config/initializers/sneakers"

  LaGear::Bus.init_pool
end
```
I'm if this helps you with Puma, but can you do something similar like:
```ruby
on_worker_boot do
  uri = URI.parse(ENV["REDIS_URL"] || "redis://localhost:6379/" )
  $redis = ConnectionPool::Wrapper.new(size: 2, timeout: 5) { Redis.new(:host => uri.host, :port => uri.port, :password => uri.password) }
  $rollout = Rollout.new($redis)
end
```

**Comment by imackinn** [comment]
@gabrieljoelc Thanks for the response so quickly on a year-old thread! 

Will take a look

**Comment by reneklacan** [comment]
Looks like this is very similar to https://github.com/FetLife/rollout/issues/30 ... closing this one as well.

Feel free to reopen it if you feel it's still an issue.

**Comment by feliperaul** [comment]
Sorry for bumping this thread closed more than 4 years ago, but we use ConnectionPool in your app and we'd like to know how to setup rollout so it can use it's connection.

Is defining the global `$redis` variable in the `on_worker_boot` as suggested by @gabrieljoelc the recommended way of doing it? Is there a way of not using a global at all?

Specially because it's using `ConnectionPool::Wrapper`, which the docs state that uses `method_missing`, so it comes with the following caveat:

```
The wrapper uses method_missing to checkout a connection, run the requested method and then immediately check the connection back into the pool. It's not high-performance so you'll want to port your performance sensitive code to use with as soon as possible.
```

**Comment by reneklacan** [comment]
@feliperaul We are currently using `ConnectionPool::Wrapper` and it has been performing well. I think you generally don't have to worry about wrapper's overhead as it's almost unelectable. The good thing is always to measure your use-case and see for yourself.

**Comment by feliperaul** [comment]
@reneklacan Could you share the code for setting up rollout with ConnectionPool that you're using?

**Comment by reneklacan** [comment]
@feliperaul it's pretty much this (simplified it a bit):

```ruby
master_group_name = '...'
sentinels = ['...']
logger = Logger.new # etc

pool_options = {
  size: ENV.fetch("CONFIG_MAX_CONCURRENCY").to_i,
  timeout: 5,
}
redis_options = {
  url: "redis://#{master_group_name}",
  role: :master,
  driver: :hiredis,
  sentinels: sentinels,
  logger: logger,
}
$redis_rollout =
  ConnectionPool::Wrapper.new(pool_options) do
    Redis.new(redis_options)
  end

$rollout = Rollout.new($redis_rollout)
```

in case you don't use sentinels, just leave it out and just use your redis url
