### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by jlecour** [FetLife/rollout#66]
Hi,

I've read the source code and tried a few feature toggles in one of my applications.

If I understand correctly, a feature is **disabled** by default. Am I right ?
If so, is there a good way to have it **enabled** by default ?

Thanks

**Comment by jlecour** [comment]
@reneklacan Hi, do you have some information about this ?
I've noticed that you've closed the issue and I'm curious if something has changed regarding this. Thanks.

**Comment by reneklacan** [comment]
@jlecour Sorry for closing without any comment.

From your description it sounds like the best solution would be having `disable_my_feature` instead of `my_feature` and check for it in your code, that way it would be enabled by default. Modifying rollout code for this use case seems unnecessary.

What do you think?
